
impressaoDeNumerosPares: imprimePares.o main.o
	gcc imprimePares.o main.o -o impressaoDeNumerosPares
imprimePares.o: imprimePares.c
	gcc -c imprimePares.c -o imprimePares.o
main.o: main.c 
	gcc -c main.c -o main.o
