/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csheets.ext.comments.ui;

import csheets.core.Cell;
import csheets.ext.comments.Comment;
import csheets.ext.comments.CommentableCell;
import csheets.ext.comments.CommentsExtension;
import csheets.notification.Notification;
import csheets.ui.ctrl.UIController;
import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author Carlos Mateus
 */
public class CommentEditUI extends javax.swing.JFrame implements Observer {

	private final CommentController commentController;

	private final UIController uiController;

	private Comment comment;

	private Comment commentOrigin;

	private Cell cell;

	private boolean newComment = false;

	/**
	 * Creates new form CommentEditUI
	 *
	 * @param uiController UIController
	 * @param comment Comment
	 */
	public CommentEditUI(UIController uiController, Comment comment) {
		this.initComponents();
		this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
		this.commentController = new CommentController(uiController);
		this.comment = new Comment(comment.userName(), comment.text(), comment.
								   getFont(), comment.getBackgroundColor(), comment.
								   getBorder());
		this.commentOrigin = comment;
		this.setLocationRelativeTo(null);
		this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
		this.uiController = uiController;
		this.update(null, null);
		Notification.commentInformer().addObserver(this);
	}

	public CommentEditUI(UIController uiController, Comment comment,
						 boolean newComment) {
		this(uiController, comment);
		this.newComment = newComment;
	}

	public CommentEditUI(UIController uiController, Comment comment,
						 boolean newComment, Cell cell) {
		this(uiController, comment);
		this.cell = cell;
		this.newComment = newComment;
	}

	@Override
	public void update(Observable o, Object arg) {
		this.jTextAreaText.setText(comment.text());
		this.jTextAreaText.setFont(this.comment.getFont());
		this.jTextAreaText.setBackground(this.comment.getBackgroundColor());
		this.jTextAreaText.setBorder(this.comment.getBorder());
		repaint();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fontButton = new javax.swing.JButton();
        backgroundButton = new javax.swing.JButton();
        borderButton = new javax.swing.JButton();
        applyButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaText = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Edit Comment");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Font");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Background");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Border");

        fontButton.setText("Edit");
        fontButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fontButtonActionPerformed(evt);
            }
        });

        backgroundButton.setText("Edit");
        backgroundButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backgroundButtonActionPerformed(evt);
            }
        });

        borderButton.setText("Edit");
        borderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borderButtonActionPerformed(evt);
            }
        });

        applyButton.setText("Apply");
        applyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyButtonActionPerformed(evt);
            }
        });

        jTextAreaText.setColumns(20);
        jTextAreaText.setRows(5);
        jScrollPane1.setViewportView(jTextAreaText);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backgroundButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fontButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(borderButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(62, 62, 62))
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(applyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fontButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(backgroundButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(borderButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(applyButton)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fontButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fontButtonActionPerformed
		commentController.changeFont(comment);
    }//GEN-LAST:event_fontButtonActionPerformed

    private void backgroundButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backgroundButtonActionPerformed
		commentController.changeBackground(comment);
    }//GEN-LAST:event_backgroundButtonActionPerformed

    private void applyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyButtonActionPerformed
		if (this.newComment) {
			String content = jTextAreaText.getText().trim();
			if (!content.isEmpty() && !"".equalsIgnoreCase(content)) {
				try {
					CommentableCell activeCell;
					if (uiController != null) {
						activeCell = (CommentableCell) uiController.
							getActiveCell().getExtension(CommentsExtension.NAME);
					} else {
						activeCell = (CommentableCell) cell.
							getExtension(CommentsExtension.NAME);
					}
					commentController.
						addComment(activeCell, content, this.comment.getFont(), this.comment.
								   getBackgroundColor(), this.comment.
								   getBorder());
				} catch (Exception ex) {
					System.out.println("ERRO ----> " + ex);
					// nothing to do here yet
				}
			}
		} else {
			this.comment.setText(this.jTextAreaText.getText());
			commentController.apply(commentOrigin, comment);
		}
		dispose();
    }//GEN-LAST:event_applyButtonActionPerformed

    private void borderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borderButtonActionPerformed
		commentController.changeBorder(comment);
    }//GEN-LAST:event_borderButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyButton;
    private javax.swing.JButton backgroundButton;
    private javax.swing.JButton borderButton;
    private javax.swing.JButton fontButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaText;
    // End of variables declaration//GEN-END:variables
}
