@startuml doc-files/crm_contacts_with_tags_design_sd_3.png


User -> TagUI : select button of contact to delete tag
TagUI -> TagController: getSelectedContact(contact)
TagController -> Persistence : repositoryFactory = repositories()
Persistence -> AppSettings : instance()
Persistence -> AppSettings : getRepositoryFactory()
create "<interface>\nRepositoryFactory"
AppSettings -> "<interface>\nRepositoryFactory" : create()
AppSettings --> Persistence : RepositoryFactory
Persistence --> TagController : RepositoryFactory
TagController -> "<interface>\nRepositoryFactory" : contactsRepository()
"<interface>\nRepositoryFactory" -> "<interface>\nContactRepository": getSelectedContact(contact)
TagController <-- "<interface>\nContactRepository": contact
TagUI <-- TagController: contact
User -> TagUI : select tag to eliminate
TagUI -> TagController: removeTag(Contact theContact, String Tag)
TagController->  "<interface>\nContact" : deleteTag(String tagName)
TagController -> "<interface>\nContactRepository": contacts()
"<interface>\nContactRepository"-> "<interface>\nContactRepository": save(contact)
TagController <-- "<interface>\nContactRepository": Contact with tag eliminated
TagUI <-- TagController: Contact with tag
User <--  TagUI: Success of operation

@enduml
