@startuml doc-files/core01_01_analyse.png
System-> User : Loads the active extensions.
User -> System: Select the extensions that want to disable it
System-> User : Disables the extensions on the menu.
@enduml
