@startuml doc-files/forms_editor_analysis.png

actor User

User->System: Starts the process.
System->User: Opens the window with options add or remove.
System->User: Presents the option to add or remove.
User->System: Chooses an option.
System->User: ask the name of the label and the textbox description
User->System: Answer.
System->User: Adds a new line.
User->System: If the chosen option is to remove.
System->User: Removes one line in the window.
@enduml