ex15:QuenteFrio.o main.o
	gcc -Wall -g QuenteFrio.o main.o -o ex15

main.o: main.c QuenteFrio.h
	gcc -c -g -Wall main.c -o main.o

operacoes.o: QuenteFrio.s
	gcc -c -g -Wall QuenteFrio.s -o QuenteFrio.o


