ex08: paraMaiusculas.o main.o
	gcc -Wall -g paraMaiusculas.o main.o -o ex08

main.o: main.c paraMaiusculas.h
	gcc -c -g -Wall main.c -o main.o

paraMaiusculas.o: paraMaiusculas.c 
	gcc -c -g -Wall paraMaiusculas.c -o paraMaiusculas.o

