@startuml doc-files/core08.1_Export_pdf_sd_design_3.png

actor User
participant "UI" as UI
participant "UIController" as UIController
participant "ExportPDFController" as ExportPDFController

participant "ExportPDF" as ExportPDF
participant "<interface>\nSpreadsheet" as Spreadsheet
participant "PDFWriter" as PDFWriter
participant "JFileChooser" as JFileChooser
participant "Value" as Value
participant "<interface>\nCell" as Cell
participant "Workbook" as Workbook




User -> UI: selects option export to pdf
UI -> UIController: ExportPDFController(UIController uiController)
UIController -> ExportXMLController: exportSelectedCells(fileChooser, uiController);
ExportXMLController -> File: file = fileChooser.getSelectedFile();
ExportPDF <-- JFileChooser: give a Selected File
ExportPDFController -> UIController: uiController.focusOwner.getSelectedCells()
ExportPDFController <-- UIController: returns SelectedCells
ExportPDFController -> EncoderStrategy: write(file,selectedCells)
ExportPDF -> ExportPDF:writeSelectedCells(selectedCells, file);
PdfWriter -> PdfWriter:getInstance(new Document(PageSize.A4), new FileOutputStream(file))
loop for every cells
Spreadsheet -> Cell:cells = cells[row][columm]
Cell -> Value:cells.getValue.toString()
PdfCell -> PdfCell : cell=new PdfCell(new Paragraph(cells, f)
PdfPTable -> PdfPTable: table = new PdfPTable(1);
PdfCell -> PdfPTable : table.add(cell)
end
@enduml