/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csheets.ext.contacts.ui;

import csheets.domain.CompanyContact;
import csheets.domain.Contact;
import csheets.domain.Event;
import csheets.ext.contacts.ContactsController;
import csheets.notification.Notification;
import java.awt.Image;
import java.util.Observable;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.tree.DefaultMutableTreeNode;

/**
 *
 * @author Martins
 */
public class CompanyView extends javax.swing.JFrame implements Observer {

	private ContactsController controller;
	private Contact contact;
	DefaultMutableTreeNode root;
	private final DefaultListModel tagsModel = new DefaultListModel();

	/**
	 * Creates new form CompanyView
	 *
	 * @param controller controller
	 * @param contact contact
	 */
	public CompanyView(ContactsController controller, Contact contact) {
		this.controller = controller;
		this.contact = contact;
		initComponents();
		this.jListTags.setModel(this.tagsModel);
		this.setLocationRelativeTo(null);
		this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
		this.setVisible(true);

		CompanyContact companyCont = (CompanyContact) this.contact;
		DefaultMutableTreeNode treeRoot = (DefaultMutableTreeNode) this.jTreeCompany.
			getModel().getRoot();
		this.root = new DefaultMutableTreeNode(companyCont.name());
		treeRoot.add(root);

		this.update(null, null);
		Notification.calendarInformer().addObserver(this);
		Notification.contactInformer().addObserver(this);
		Notification.eventInformer().addObserver(this);
	}

	@Override
	public void update(Observable o, Object arg) {
		try {
			this.jLabelCompanyPhoto.setIcon(new ImageIcon(this.controller.
				contactPhoto(contact).getScaledInstance(this.jLabelCompanyPhoto.
				getWidth(), this.jLabelCompanyPhoto.getHeight(), Image.SCALE_SMOOTH)));
			this.jLabelCompanyName.setText(this.contact.name());
			this.jTreeCompany.removeAll();
			for (Contact contactPer : this.controller.contactsCompany(contact)) {
				DefaultMutableTreeNode contactRoot = new DefaultMutableTreeNode(contactPer);
				root.add(contactRoot);
				for (Event event : this.controller.eventsContact(contactPer)) {
					DefaultMutableTreeNode eventRoot = new DefaultMutableTreeNode(event);
					contactRoot.add(eventRoot);
				}
			}
			this.jTreeCompany.revalidate();
			this.jTreeCompany.repaint();
		} catch (Exception ex) {
			Logger.getLogger(CompanyView.class.getName()).
				log(Level.SEVERE, null, ex);
		}
		this.tagsModel.removeAllElements();
		for (String tag : this.contact.tags()) {
			this.tagsModel.addElement(tag);
		}
		this.revalidate();
		this.repaint();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTreeCompany = new javax.swing.JTree();
        jLabelAgenda = new javax.swing.JLabel();
        jLabelCompanyPhoto = new javax.swing.JLabel();
        jLabelCompanyName = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListTags = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        jTreeCompany.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(jTreeCompany);

        jLabelAgenda.setText("Agenda:");

        jLabelCompanyPhoto.setBackground(new java.awt.Color(0, 0, 0));

        jLabelCompanyName.setText("Company Name");

        jScrollPane2.setViewportView(jListTags);

        jLabel1.setText("Tags:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelCompanyPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelCompanyName)))
                        .addGap(0, 51, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCompanyPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabelCompanyName)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelAgenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAgenda;
    private javax.swing.JLabel jLabelCompanyName;
    private javax.swing.JLabel jLabelCompanyPhoto;
    private javax.swing.JList<String> jListTags;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTree jTreeCompany;
    // End of variables declaration//GEN-END:variables

}
