ex09: ordenaVetor.o organizaVetor.o main.o
	gcc ordenaVetor.o organizaVetor.o main.o -o ex09
	
organizaVetor.o: organizaVetor.c 
	gcc -c  organizaVetor.c -o organizaVetor.o

ordenaVetor.o: ordenaVetor.c
	gcc -c ordenaVetor.c -o ordenaVetor.o

main.o: main.c 
	gcc -c main.c -o main.o

