/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csheets.ext.task.ui;

import csheets.domain.Contact;
import csheets.domain.Event;
import csheets.domain.Reminder;
import csheets.domain.Task;
import csheets.ext.events.EventsController;
import csheets.ext.reminder.ReminderController;
import csheets.ext.task.TaskController;
import csheets.framework.persistence.repositories.DataIntegrityViolationException;
import csheets.support.DateTime;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JOptionPane;

/**
 *
 * @author Bruno
 */
public class TaskManager extends javax.swing.JPanel implements Observer {

    private final TaskController controller;
    private EventsController eventsController;
    private ReminderController reminderController;
    private final Task task;
    private List<Contact> listContacts = new ArrayList();

    private final String[] nameMonth = {"Invalid", "January", "Febraury",
        "March", "April", "May", "June",
        "July", "August", "September",
        "October", "November", "December"};
    private Calendar timeStep;

    /**
     * Creates new form EditTaskFrame
     *
     * @param controller Controller
     * @param task Task
     */
    public TaskManager(TaskController controller, Task task) {
        this.controller = controller;
        this.task = task;
        initComponents();
        initContact();
        this.update(null, task);
        initDate();
        this.PanelDealiningbyEventRemi.setVisible(false);
        this.PanelDealining.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelPriority = new javax.swing.JLabel();
        jLabelPercentage = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldDescription = new javax.swing.JTextField();
        jComboBoxPriority = new javax.swing.JComboBox();
        jTextFieldPercentage = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxContact = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        checkBoxEvent = new javax.swing.JCheckBox();
        CheckBoxReminder = new javax.swing.JCheckBox();
        PanelDealiningbyEventRemi = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lbloption = new javax.swing.JLabel();
        cmbEventsR = new javax.swing.JComboBox<>();
        lbldata = new javax.swing.JLabel();
        PanelDealining = new javax.swing.JPanel();
        cmbYear = new javax.swing.JComboBox();
        cmbMonth = new javax.swing.JComboBox();
        cmbDay = new javax.swing.JComboBox();
        checkDeadline = new javax.swing.JCheckBox();

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane1.setViewportView(jTextArea2);

        jLabel1.setText("TaskName");

        jLabel2.setText("Description");

        jLabelPriority.setText("Priority");

        jLabelPercentage.setText("Percentage");

        jComboBoxPriority.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));

        jLabel3.setText("Contact");

        jLabel4.setText("Connect To: ");

        checkBoxEvent.setText("Event");
        checkBoxEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxEventActionPerformed(evt);
            }
        });

        CheckBoxReminder.setText("Reminder");
        CheckBoxReminder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxReminderActionPerformed(evt);
            }
        });

        jLabel5.setText("Deadline");

        lbloption.setText("Events");

        cmbEventsR.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbEventsRItemStateChanged(evt);
            }
        });

        lbldata.setText("    ");

        javax.swing.GroupLayout PanelDealiningbyEventRemiLayout = new javax.swing.GroupLayout(PanelDealiningbyEventRemi);
        PanelDealiningbyEventRemi.setLayout(PanelDealiningbyEventRemiLayout);
        PanelDealiningbyEventRemiLayout.setHorizontalGroup(
            PanelDealiningbyEventRemiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDealiningbyEventRemiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDealiningbyEventRemiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDealiningbyEventRemiLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(lbldata, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PanelDealiningbyEventRemiLayout.createSequentialGroup()
                        .addComponent(lbloption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbEventsR, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        PanelDealiningbyEventRemiLayout.setVerticalGroup(
            PanelDealiningbyEventRemiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDealiningbyEventRemiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelDealiningbyEventRemiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbloption)
                    .addComponent(cmbEventsR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelDealiningbyEventRemiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbldata))
                .addContainerGap())
        );

        cmbYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbYearActionPerformed(evt);
            }
        });

        cmbMonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMonthActionPerformed(evt);
            }
        });

        cmbDay.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout PanelDealiningLayout = new javax.swing.GroupLayout(PanelDealining);
        PanelDealining.setLayout(PanelDealiningLayout);
        PanelDealiningLayout.setHorizontalGroup(
            PanelDealiningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDealiningLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbYear, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(cmbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelDealiningLayout.setVerticalGroup(
            PanelDealiningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDealiningLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelDealiningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbYear, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        checkDeadline.setText("Deadline");
        checkDeadline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkDeadlineActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabelPercentage)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabelPriority, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jComboBoxPriority, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3))
                            .addGap(15, 15, 15)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBoxContact, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checkBoxEvent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CheckBoxReminder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkDeadline))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PanelDealining, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PanelDealiningbyEventRemi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(36, 36, 36))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPriority)
                    .addComponent(jComboBoxPriority, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPercentage)
                    .addComponent(jTextFieldPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(checkBoxEvent)
                    .addComponent(CheckBoxReminder)
                    .addComponent(checkDeadline))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelDealiningbyEventRemi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelDealining, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbYearActionPerformed

    private void cmbMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMonthActionPerformed
        initDays();
    }//GEN-LAST:event_cmbMonthActionPerformed

    private void checkBoxEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxEventActionPerformed
        //Event CheckBox
        if (this.CheckBoxReminder.isSelected() || this.checkDeadline.
                isSelected()) {
            this.CheckBoxReminder.setSelected(false);
            this.checkDeadline.setSelected(false);
        }
        if (this.checkBoxEvent.isSelected()) {
            this.PanelDealiningbyEventRemi.setVisible(true);
            this.PanelDealining.setVisible(false);
            this.cmbEventsR.removeAllItems();
            this.lbloption.setText("Events");
            loadEvents();
        } else {
            this.PanelDealiningbyEventRemi.setVisible(false);
        }
    }//GEN-LAST:event_checkBoxEventActionPerformed

    private void CheckBoxReminderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxReminderActionPerformed
        /**
         * CheckBoxReminder whenever the CheckBoxReminder is selected, the
         * listBox, will be visible, which will have all created reminders, will
         * be visible. and automatically the other boxes unselected.
         */
        if (this.checkBoxEvent.isSelected() || this.checkDeadline.isSelected()) {
            this.checkBoxEvent.setSelected(false);
            this.checkDeadline.setSelected(false);
        }
        if (this.CheckBoxReminder.isSelected()) {
            this.PanelDealiningbyEventRemi.setVisible(true);
            this.PanelDealining.setVisible(false);
            this.cmbEventsR.removeAllItems();
            this.lbloption.setText("Reminders");
            loadReminders();
        } else {
            this.PanelDealiningbyEventRemi.setVisible(false);
        }
    }//GEN-LAST:event_CheckBoxReminderActionPerformed
    /**
     * Combobox that will be loaded, events and reminders
     * @param evt event or reminders. 
     */
    private void cmbEventsRItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbEventsRItemStateChanged
        if (cmbEventsR.getSelectedItem() != null) {
            if (this.cmbEventsR.getSelectedItem() instanceof Event) {
                Event event = (Event) this.cmbEventsR.getSelectedItem();
                this.lbldata.setText(DateTime.format(event.endDate()));
            } else {
                Reminder reminder = (Reminder) this.cmbEventsR.getSelectedItem();
                this.lbldata.setText(DateTime.format(reminder.timeOfReminder()));
            }
        }
    }//GEN-LAST:event_cmbEventsRItemStateChanged

    private void checkDeadlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkDeadlineActionPerformed
        //the panel is visible to set the date, if the check is Selected. 
        if (this.checkBoxEvent.isSelected() || this.CheckBoxReminder.
                isSelected()) {
            this.checkBoxEvent.setSelected(false);
            this.CheckBoxReminder.setSelected(false);
        }
        if (this.checkDeadline.isSelected()) {
            this.PanelDealiningbyEventRemi.setVisible(false);
            this.PanelDealining.setVisible(true);
        } else {
            this.PanelDealining.setVisible(false);
        }

    }//GEN-LAST:event_checkDeadlineActionPerformed

    private void initDate() {
        initYear();
        initMonth();
        initDays();

    }

    private void initYear() {
        Calendar calendar = Calendar.getInstance();
        cmbYear.removeAllItems();
        int currentYear = calendar.get(Calendar.YEAR);

        for (int yearCount = currentYear; yearCount <= currentYear + 10; yearCount++) {
            cmbYear.addItem(yearCount);
        }
        cmbYear.setSelectedIndex(0);
    }

    private void initMonth() {
        Calendar calendar = Calendar.getInstance();
        cmbMonth.removeAllItems();
        for (int monthCount = 1; monthCount < 13; monthCount++) {
            cmbMonth.addItem(nameMonth[monthCount]);
        }
        cmbMonth.setSelectedIndex(calendar.get(Calendar.MONTH));
    }

    private void initDays() {
        Calendar calendar = Calendar.getInstance();
        cmbDay.removeAllItems();
        calendar.set(Calendar.MONTH, cmbMonth.getSelectedIndex());
        calendar.set(Calendar.YEAR, cmbYear.getSelectedIndex());

        int lastDay = calendar.getActualMaximum(Calendar.DAY_OF_MONTH);

        for (int dayCount = 1; dayCount <= lastDay; dayCount++) {
            cmbDay.addItem(dayCount);
        }
        cmbDay.setSelectedIndex(calendar.get(Calendar.DAY_OF_MONTH));
    }

    /**
     * This method return the date of reminder.
     *
     * @return name
     */
    public Calendar timeOfReminder() {
        return this.timeStep;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBoxReminder;
    private javax.swing.JPanel PanelDealining;
    private javax.swing.JPanel PanelDealiningbyEventRemi;
    private javax.swing.JCheckBox checkBoxEvent;
    private javax.swing.JCheckBox checkDeadline;
    private javax.swing.JComboBox cmbDay;
    private javax.swing.JComboBox<Object> cmbEventsR;
    private javax.swing.JComboBox cmbMonth;
    private javax.swing.JComboBox cmbYear;
    private javax.swing.JComboBox<String> jComboBoxContact;
    private javax.swing.JComboBox jComboBoxPriority;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelPercentage;
    private javax.swing.JLabel jLabelPriority;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextFieldDescription;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPercentage;
    private javax.swing.JLabel lbldata;
    private javax.swing.JLabel lbloption;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        if (this.task != null) {
            this.jTextFieldName.setText(this.task.TaskName());
            this.jTextFieldDescription.setText(this.task.Description());
            this.jComboBoxPriority.setSelectedIndex(this.task.Priority() - 1);
            this.jTextFieldPercentage.setText(String.valueOf(this.task.
                    Percentage()));
            this.jComboBoxContact.setEnabled(false);
            this.checkBoxEvent.setSelected(false);
            this.CheckBoxReminder.setSelected(false);
            this.checkDeadline.setSelected(false);
            if (this.task.getDeadLineEvent() != null) {
                this.checkBoxEvent.setSelected(true);
                this.cmbEventsR.setSelectedItem(this.task.getDeadLineEvent());
            } else if (this.task.getDeadLineReminder() != null) {
                this.CheckBoxReminder.setSelected(true);
                this.cmbEventsR.setSelectedItem(this.task.getDeadLineReminder());
            } else if (this.task.getDeadLineTime() != null) {
                this.checkDeadline.setSelected(true);
                this.cmbYear.setSelectedItem(String.valueOf(DateTime.
                        year(this.task.
                                getDeadLineTime())) + "/");
                this.cmbMonth.setSelectedItem(String.valueOf(DateTime.
                        month(this.task.
                                getDeadLineTime())) + "/");
                this.cmbDay.setSelectedItem(String.valueOf(DateTime.
                        day(this.task.
                                getDeadLineTime())));
            }
        }
    }

    private void initContact() {
        for (Contact contact : this.controller.allContacts()) {
            this.listContacts.add(contact);
            this.jComboBoxContact.addItem(contact.toString());
        }
    }

    /**
     * the responsible method of creating TAKS.
     *
     * @throws DataIntegrityViolationException
     */
    public void createTask() throws DataIntegrityViolationException {
        try {
            Object obj = null;
            if (checkBoxEvent.isSelected() || CheckBoxReminder.isSelected()) {
                obj = this.cmbEventsR.getSelectedItem();
            } else if (checkDeadline.isSelected()) {
                obj = DateTime.newCalendar((Integer) (this.cmbYear.
                        getSelectedItem()), cmbMonth.getSelectedIndex() + 1, (Integer) (this.cmbDay.
                        getSelectedItem()));
            }
            if (this.task == null) {
                this.controller.
                        createTask(this.jTextFieldName.getText(), this.jTextFieldDescription.
                                getText(), this.jComboBoxPriority.
                                getSelectedIndex() + 1, Float.
                                parseFloat(this.jTextFieldPercentage.getText()), (Contact) this.listContacts.
                                get(this.jComboBoxContact.getSelectedIndex()), obj);

            } else {
                this.task.
                        defineTask(this.jTextFieldName.getText(), this.jTextFieldDescription.
                                getText(), this.jComboBoxPriority.
                                getSelectedIndex() + 1, Float.
                                parseFloat(this.jTextFieldPercentage.getText()), obj);
                this.controller.editTask(this.task);
            }
        } catch (IllegalArgumentException ex) {
            JOptionPane.
                    showMessageDialog(null, "Illegal arguments", "Create/Edit Task", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * Method to loading Events
     */
    private void loadEvents() {
        for (Event event : this.controller.allEvents()) {
            this.cmbEventsR.addItem(event);
        }
        revalidate();
        repaint();
    }

    /**
     * Method to loading Reminders.
     */
    private void loadReminders() {
        for (Reminder reminder : this.controller.allReminders()) {
            this.cmbEventsR.addItem(reminder);
        }
        revalidate();
        repaint();
    }
}
