/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csheets.ui.legacy.importXML.ui;

import csheets.ui.ctrl.UIController;
import csheets.ui.legacy.importXML.ImportXMLController;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author ruben
 */
public class ImportXMLPanel extends javax.swing.JFrame {

	private final ImportXMLController controller;
	private UIController uiController;

	/**
	 * Creates new form ExportXMLPanel
	 *
	 * @param uiController uiController
	 */
	public ImportXMLPanel(UIController uiController) {
		initComponents();
		this.uiController = uiController;
		this.controller = new ImportXMLController(this.uiController);
		initiateOptions();
		this.jComboBoxSpreedSheet.setEnabled(false);
	}

	/**
	 * Method to add Items
	 */
	private void initiateOptions() {
		this.jComboBoxType.removeAll();
		this.jComboBoxType.addItem("Workbook");
		this.jComboBoxType.addItem("SpreedSheet");
		this.jComboBoxType.addItem("SpreedSheet Selected");
		this.jComboBoxSpreedSheet.removeAll();
		for (int i = 0; i < this.uiController.getActiveWorkbook().
			getSpreadsheetCount(); i++) {
			this.jComboBoxSpreedSheet.addItem(this.uiController.
				getActiveWorkbook().getSpreadsheet(i).getTitle());
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        checkbox1 = new java.awt.Checkbox();
        jLabel8 = new javax.swing.JLabel();
        CellFontTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        CommentTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        BackgroundTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        BorderTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        ValueTextField = new javax.swing.JTextField();
        jTextFieldTagColumn1 = new javax.swing.JTextField();
        jButtonImport = new javax.swing.JButton();
        jComboBoxType = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxSpreedSheet = new javax.swing.JComboBox<>();
        jToggleButtonCancel = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldTagColumn = new javax.swing.JTextField();
        jTextFieldTagWorkbook = new javax.swing.JTextField();
        jTextFieldTagSpreadSheet = new javax.swing.JTextField();
        jTextFieldTagRow = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldValue = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        FontTextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        backgroundTextField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        TextFieldComment = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        ForegroundTextField = new javax.swing.JTextField();
        HorizontalTextField = new javax.swing.JTextField();
        VerticalTextField = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        AuthorTextField = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        ScriptsTextField = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        ScriptTextField = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        NameTextField = new javax.swing.JTextField();
        TypeTextField = new javax.swing.JTextField();
        ContentTextField = new javax.swing.JTextField();
        SynchronousTextField = new javax.swing.JTextField();

        checkbox1.setLabel("export selected");

        jLabel8.setText("Font");

        CellFontTextField.setText("Font");
        CellFontTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CellFontTextFieldActionPerformed(evt);
            }
        });

        jLabel9.setText("Comment");

        CommentTextField.setText("Comment");
        CommentTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CommentTextFieldActionPerformed(evt);
            }
        });

        jLabel10.setText("Background");

        BackgroundTextField.setText("Background");
        BackgroundTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackgroundTextFieldActionPerformed(evt);
            }
        });

        jLabel11.setText("Border");

        BorderTextField.setText("Border");

        jLabel12.setText("Value");

        ValueTextField.setText("Value");

        jTextFieldTagColumn1.setText("Column");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonImport.setText("Import");
        jButtonImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImportActionPerformed(evt);
            }
        });

        jComboBoxType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTypeActionPerformed(evt);
            }
        });

        jLabel1.setText("Type:");

        jLabel2.setText("SpreedSheet:");

        jToggleButtonCancel.setText("Cancel");
        jToggleButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonCancelActionPerformed(evt);
            }
        });

        jLabel3.setText("WoorkBook:");

        jLabel4.setText("SpreadSheet:");

        jLabel5.setText("Row:");

        jLabel6.setText("Column:");

        jTextFieldTagColumn.setText("Column");

        jTextFieldTagWorkbook.setText("WorkBook");

        jTextFieldTagSpreadSheet.setText("SpreadSheet");
        jTextFieldTagSpreadSheet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTagSpreadSheetActionPerformed(evt);
            }
        });

        jTextFieldTagRow.setText("Row");

        jLabel7.setText("Tags");

        jLabel13.setText("Value:");

        jTextFieldValue.setText("Value");
        jTextFieldValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValueActionPerformed(evt);
            }
        });

        jLabel14.setText("Font:");

        FontTextField.setText("Font");

        jLabel15.setText("Background:");

        backgroundTextField.setText("Background");

        jLabel16.setText("Border:");

        jTextField1.setText("Border");

        jLabel17.setText("Comment:");

        TextFieldComment.setText("Comment");
        TextFieldComment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldCommentActionPerformed(evt);
            }
        });

        jLabel18.setText("Foreground:");

        jLabel19.setText("Horizontal:");

        jLabel20.setText("Vertical:");

        ForegroundTextField.setText("Foreground");
        ForegroundTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ForegroundTextFieldActionPerformed(evt);
            }
        });

        HorizontalTextField.setText("Horizontal");

        VerticalTextField.setText("Vertical");

        jLabel21.setText("Author:");

        AuthorTextField.setText("CommentAuthor");
        AuthorTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AuthorTextFieldActionPerformed(evt);
            }
        });

        jLabel22.setText("Scripts:");

        ScriptsTextField.setText("Scripts");

        jLabel23.setText("Script:");

        ScriptTextField.setText("Script");
        ScriptTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScriptTextFieldActionPerformed(evt);
            }
        });

        jLabel24.setText("Name:");

        jLabel25.setText("Type:");

        jLabel26.setText("Content:");

        jLabel27.setText("Synchronous:");

        NameTextField.setText("Name");

        TypeTextField.setText("Type");

        ContentTextField.setText("Content");

        SynchronousTextField.setText("Synchronous");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 19, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(56, 56, 56))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonImport)
                                .addGap(27, 27, 27)
                                .addComponent(jToggleButtonCancel)
                                .addGap(22, 22, 22))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxSpreedSheet, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldTagSpreadSheet, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldTagRow)
                            .addComponent(jTextFieldTagWorkbook)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel14)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel17)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldTagColumn)
                            .addComponent(jTextFieldValue)
                            .addComponent(FontTextField)
                            .addComponent(backgroundTextField)
                            .addComponent(jTextField1)
                            .addComponent(ForegroundTextField)
                            .addComponent(HorizontalTextField)
                            .addComponent(VerticalTextField)
                            .addComponent(TextFieldComment)
                            .addComponent(AuthorTextField)
                            .addComponent(ScriptsTextField)
                            .addComponent(ScriptTextField)
                            .addComponent(NameTextField)
                            .addComponent(TypeTextField)
                            .addComponent(ContentTextField)
                            .addComponent(SynchronousTextField))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxSpreedSheet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldTagWorkbook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldTagSpreadSheet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldTagRow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldTagColumn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(FontTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(backgroundTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(ForegroundTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(HorizontalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(VerticalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldComment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(AuthorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(ScriptsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(ScriptTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(TypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(ContentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(SynchronousTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButtonCancel)
                    .addComponent(jButtonImport))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImportActionPerformed
		JFileChooser fileChooser = new JFileChooser();
		FileFilter filter = new FileNameExtensionFilter("XML Files", "xml");
		fileChooser.setFileFilter(filter);
		int returnVal = fileChooser.showOpenDialog(fileChooser);

		String path = "";
		if (returnVal == JFileChooser.APPROVE_OPTION) {
			path = fileChooser.getSelectedFile().
				getAbsolutePath();
			try {

				switch (this.jComboBoxType.getSelectedIndex()) {
					case 0:
						try {
							this.controller.
								importWorkbook(path, this.jTextFieldTagWorkbook.
											   getText(), this.jTextFieldTagSpreadSheet.
											   getText(), this.jTextFieldTagRow.
											   getText(), this.jTextFieldTagColumn.
											   getText(), this.ValueTextField.
											   getText(), this.FontTextField.
											   getText(), this.BackgroundTextField.
											   getText(), this.BorderTextField.
											   getText(), this.ForegroundTextField.
											   getText(), this.HorizontalTextField.
											   getText(), this.VerticalTextField.
											   getText(), this.TextFieldComment.
											   getText(), this.AuthorTextField.
											   getText(), this.ScriptsTextField.
											   getText(), this.ScriptTextField.
											   getText(), this.NameTextField.
											   getText(), this.TypeTextField.
											   getText(), this.ContentTextField.
											   getText(), this.SynchronousTextField.
											   getText());
						} catch (IOException ex) {
							JOptionPane.
								showMessageDialog(this, ex.getMessage(), "Ficheiro Invalido", JOptionPane.ERROR_MESSAGE);
						}
						break;
					case 1:

						this.controller.
							importSpreadSheet(path, this.jTextFieldTagSpreadSheet.
											  getText(), this.jTextFieldTagRow.
											  getText(), this.jTextFieldTagColumn.
											  getText(), this.ValueTextField.
											  getText(), this.FontTextField.
											  getText(), this.BackgroundTextField.
											  getText(), this.BorderTextField.
											  getText(), this.ForegroundTextField.
											  getText(), this.HorizontalTextField.
											  getText(), this.VerticalTextField.
											  getText(), this.TextFieldComment.
											  getText(), this.AuthorTextField.
											  getText(), this.uiController.
											  getActiveWorkbook().
											  getSpreadsheet(this.jComboBoxSpreedSheet.
												  getSelectedIndex()));

						break;
					default:
						this.controller.
							importSpreadSheetSelected(path, this.jTextFieldTagSpreadSheet.
													  getText(), this.jTextFieldTagRow.
													  getText(), this.jTextFieldTagColumn.
													  getText());
						break;
				}
				this.dispose();
			} catch (Exception ex) {
				ex.printStackTrace();
			}
		}
    }//GEN-LAST:event_jButtonImportActionPerformed

    private void jToggleButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonCancelActionPerformed
		this.dispose();
    }//GEN-LAST:event_jToggleButtonCancelActionPerformed

    private void jComboBoxTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTypeActionPerformed
		if (this.jComboBoxType.getSelectedIndex() == 1) {
			this.jComboBoxSpreedSheet.setEnabled(true);
		} else {
			this.jComboBoxSpreedSheet.setEnabled(false);
		}
    }//GEN-LAST:event_jComboBoxTypeActionPerformed

    private void jTextFieldTagSpreadSheetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTagSpreadSheetActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTagSpreadSheetActionPerformed

    private void CellFontTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CellFontTextFieldActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_CellFontTextFieldActionPerformed

    private void CommentTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CommentTextFieldActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_CommentTextFieldActionPerformed

    private void BackgroundTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackgroundTextFieldActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_BackgroundTextFieldActionPerformed

    private void jTextFieldValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValueActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValueActionPerformed

    private void TextFieldCommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldCommentActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_TextFieldCommentActionPerformed

    private void ForegroundTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForegroundTextFieldActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_ForegroundTextFieldActionPerformed

    private void AuthorTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AuthorTextFieldActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_AuthorTextFieldActionPerformed

    private void ScriptTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScriptTextFieldActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_ScriptTextFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AuthorTextField;
    private javax.swing.JTextField BackgroundTextField;
    private javax.swing.JTextField BorderTextField;
    private javax.swing.JTextField CellFontTextField;
    private javax.swing.JTextField CommentTextField;
    private javax.swing.JTextField ContentTextField;
    private javax.swing.JTextField FontTextField;
    private javax.swing.JTextField ForegroundTextField;
    private javax.swing.JTextField HorizontalTextField;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JTextField ScriptTextField;
    private javax.swing.JTextField ScriptsTextField;
    private javax.swing.JTextField SynchronousTextField;
    private javax.swing.JTextField TextFieldComment;
    private javax.swing.JTextField TypeTextField;
    private javax.swing.JTextField ValueTextField;
    private javax.swing.JTextField VerticalTextField;
    private javax.swing.JTextField backgroundTextField;
    private java.awt.Checkbox checkbox1;
    private javax.swing.JButton jButtonImport;
    private javax.swing.JComboBox<String> jComboBoxSpreedSheet;
    private javax.swing.JComboBox<String> jComboBoxType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextFieldTagColumn;
    private javax.swing.JTextField jTextFieldTagColumn1;
    private javax.swing.JTextField jTextFieldTagRow;
    private javax.swing.JTextField jTextFieldTagSpreadSheet;
    private javax.swing.JTextField jTextFieldTagWorkbook;
    private javax.swing.JTextField jTextFieldValue;
    private javax.swing.JToggleButton jToggleButtonCancel;
    // End of variables declaration//GEN-END:variables

}
