ex12: vec_corta.o main.o
	gcc -Wall -g vec_corta.o main.o -o ex12

main.o: main.c vec_corta.h
	gcc -c -g -Wall main.c -o main.o

vec_corta.o: vec_corta.s
	gcc -c -g -Wall vec_corta.s -o vec_corta.o


