@startuml doc-files/analysis_CRM_5_3.png

User -> System: Select agenda
System-> User : Display events for current day and user
loop
User -> System: Change selected user or day
System-> User : Display events for selected day and user
end
@enduml
