/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csheets.ui.FormEditor.ui;

import csheets.notification.Notification;
import javax.swing.JOptionPane;

/**
 *
 * @author João Martins
 */
public class LabelPanel extends javax.swing.JPanel {

	/**
	 * Creates new form LabelPanel
	 *
	 * @param content Content
	 */
	public LabelPanel(String content) {
		initComponents();
		this.jLabel1.setText(content);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        removeLine = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        removeLine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csheets/res/img/delete.gif"))); // NOI18N
        removeLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeLineActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(removeLine))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
            .addComponent(removeLine)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void removeLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeLineActionPerformed

		int op = JOptionPane.
			showConfirmDialog(this, "Do you want to remove " + this.jLabel1.
							  getText() + " " + "?", "Remove Event", JOptionPane.OK_CANCEL_OPTION);

		if (JOptionPane.OK_OPTION == op) {
			Notification.formInformer().notifyChange(this);
		}
    }//GEN-LAST:event_removeLineActionPerformed

	/**
	 *
	 * @return content of label
	 */
	public String getContent() {
		return this.jLabel1.getText();
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton removeLine;
    // End of variables declaration//GEN-END:variables
}
