  @startuml doc-files/lang07.2_manager_edit.png
  participant User as us
  participant EditCreateScriptUI as ui
  participant MacroBeanShellController as controller
  participant Code as code
  participant UIController as uicontrol
  participant Workbook as work

  activate ui
	us -> ui : selects edit script
	create controller
	ui -> controller : new()
  deactivate ui
	us <-- ui : asks info
    us -> ui : introduces
  activate ui
  activate controller
	ui -> controller : saveScript()
  deactivate ui
	controller -> uicontrol : getUIController()
  activate uicontrol
	uicontrol -> work : getActiveWorkbook()
  deactivate uicontrol
  activate work
	work-> work: getScript(name)
	controller <- work : script
	controller -> work : remove(script)
  deactivate controller
	work -> work : remove(script)
  deactivate work
    create code
  activate controller
	controller -> code : new(name, type, content, exec)
	controller -> work : save(script)
  deactivate controller
	activate work
    deactivate uicontrol
	work -> work : addScript()
  deactivate work
	activate ui
	us <-- ui : display scripts
	deactivate ui
  @enduml