
ex11: concatena.o paraMaiusculas.o testaInverso.o main.o
	gcc  -Wall  concatena.o paraMaiusculas.o testaInverso.o main.o -o ex09
	
testaInverso.o: testaInverso.c 
	gcc -c -Wall testaInverso.c -o testaInverso.o

paraMaiusculas.o: paraMaiusculas.c
	gcc -c -Wall paraMaiusculas.c -o paraMaiusculas.o

concatena.o: concatena.c
	gcc -c -Wall concatena.c -o concatena.o

main.o: main.c 
	gcc -c -Wall  main.c -o main.o

