@startuml doc-files/export_file_image.png

actor User
participant "<<analysis>>\nExportFileUI" as ExportFileUI
participant "<<analysis>>\nExportFileController" as ExportFileController
participant "<<analysis>>\nUI" as UI

User->ExportFileUI: Export File
ExportFileUI->ExportFileController: content = getContent(cells, separator, header)
ExportFileUI->ExportFileController: export(content, path)

ExportFileUI->User: Exported successfully

@enduml