@startuml doc-files/import_file_image.png

actor User
participant "<<analysis>>\nImportTextFileUI" as ImportTextFileUI
participant "<<analysis>>\nImportTextFileController" as ImportTextFileController

User->ImportTextFileUI: chooses file and his options
ImportTextFileUI->ImportTextFileController: new ()

activate ImportTextFileController
ImportTextFileUI->ImportTextFileController: import()
ImportTextFileUI->ImportTextFileController: parse(character, boolean header, cells)
ImportTextFileController->ImportTextFileUI: cells
deactivate ImportTextFileController


@enduml