/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csheets.ext.chat.ui;

import csheets.ext.chat.ChatController;
import csheets.ext.chat.domain.Room;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JPanel;

/**
 *
 * @author valhalla
 */
public class RoomsPanelSingle extends javax.swing.JPanel implements Observer {

	private ChatController controller;
	private Room room;
	private JPanel jPanelColor;

	/**
	 * Creates new form ChatPanelUser
	 */
	public RoomsPanelSingle(ChatController controller, Room room) {
		this.controller = controller;
		this.room = room;
		this.initComponents();
		this.setBorder(javax.swing.BorderFactory.createTitledBorder(room.type().
			toString()));
		this.update(null, null);
	}

	@Override
	public void update(Observable o, Object arg) {
		this.jLabelName.setText(this.room.name());
		this.jLabelOwner.setText(this.room.creator().name());
		this.revalidate();
		this.repaint();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelName = new javax.swing.JLabel();
        jLabelOwner = new javax.swing.JLabel();
        jButtonInteraction = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("type"));
        setMaximumSize(new java.awt.Dimension(290, 77));
        setMinimumSize(new java.awt.Dimension(290, 77));
        setSize(new java.awt.Dimension(290, 77));

        jLabelName.setText("nickname");

        jLabelOwner.setFont(new java.awt.Font("Lucida Grande", 1, 11)); // NOI18N
        jLabelOwner.setText("user");

        jButtonInteraction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csheets/res/img/edit.png"))); // NOI18N
        jButtonInteraction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInteractionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelName, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                    .addComponent(jLabelOwner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonInteraction)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelOwner)
                        .addGap(5, 5, 5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonInteraction)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInteractionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInteractionActionPerformed
		new InteractionFrame(this.controller, this.room);
    }//GEN-LAST:event_jButtonInteractionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonInteraction;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelOwner;
    // End of variables declaration//GEN-END:variables
}
