/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csheets.ext.chat.ui;

import csheets.ext.chat.ChatController;
import csheets.ext.chat.domain.User;
import csheets.support.CirclePanel;
import java.awt.Dimension;
import java.awt.Image;
import java.util.Observable;
import java.util.Observer;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author valhalla
 */
public class UsersPanelSingle extends javax.swing.JPanel implements Observer {

	private ChatController controller;
	private User user;
	private JPanel jPanelColor;

	/**
	 * Creates new form ChatPanelUser
	 */
	public UsersPanelSingle(ChatController controller, User user) {
		this.controller = controller;
		this.user = user;
		this.initComponents();
		this.update(null, null);
	}

	@Override
	public void update(Observable o, Object arg) {
		this.jLabelNick.setText(this.user.nickname());
		this.jLabelName.setText(this.user.name());
		if (this.user.image() != null) {
			ImageIcon img = new ImageIcon(this.user.image());
			Image newImg = img.getImage().getScaledInstance(this.jLabelPhoto.
				getWidth(), this.jLabelPhoto.getHeight(), Image.SCALE_SMOOTH);
			this.jLabelPhoto.setIcon(new ImageIcon(newImg));
		}
		if (this.user.state() == User.State.ONLINE) {
			this.jLabelStatus.setText(User.State.ONLINE.toString());
			this.jPanelColor = CirclePanel.
				createCircle(new Dimension(20, 20), this.controller.
							 stateColor(User.State.ONLINE));
		} else if (this.user.state() == User.State.AWAY) {
			this.jLabelStatus.setText(User.State.AWAY.toString());
			this.jPanelColor = CirclePanel.
				createCircle(new Dimension(20, 20), this.controller.
							 stateColor(User.State.AWAY));
		} else {
			this.jLabelStatus.setText(User.State.OFFLINE.toString());
			this.jPanelColor = CirclePanel.
				createCircle(new Dimension(20, 20), this.controller.
							 stateColor(User.State.OFFLINE));
		}
		this.jPanelStatus.removeAll();
		this.jPanelStatus.add(this.jPanelColor);
		this.revalidate();
		this.repaint();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPhoto = new javax.swing.JLabel();
        jLabelNick = new javax.swing.JLabel();
        jPanelStatus = new javax.swing.JPanel();
        jLabelStatus = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jButtonInteraction = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setMaximumSize(new java.awt.Dimension(290, 77));
        setMinimumSize(new java.awt.Dimension(290, 77));
        setSize(new java.awt.Dimension(290, 77));

        jLabelPhoto.setMaximumSize(new java.awt.Dimension(60, 60));
        jLabelPhoto.setMinimumSize(new java.awt.Dimension(60, 60));
        jLabelPhoto.setPreferredSize(new java.awt.Dimension(60, 60));
        jLabelPhoto.setSize(new java.awt.Dimension(60, 60));

        jLabelNick.setText("nickname");

        jPanelStatus.setMaximumSize(new java.awt.Dimension(20, 20));
        jPanelStatus.setMinimumSize(new java.awt.Dimension(20, 20));
        jPanelStatus.setSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPanelStatusLayout = new javax.swing.GroupLayout(jPanelStatus);
        jPanelStatus.setLayout(jPanelStatusLayout);
        jPanelStatusLayout.setHorizontalGroup(
            jPanelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanelStatusLayout.setVerticalGroup(
            jPanelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jLabelStatus.setText("state");

        jLabelName.setFont(new java.awt.Font("Lucida Grande", 1, 11)); // NOI18N
        jLabelName.setText("user");

        jButtonInteraction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csheets/res/img/edit.png"))); // NOI18N
        jButtonInteraction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInteractionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNick, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelStatus))
                            .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(jButtonInteraction)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelNick)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanelStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelStatus, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonInteraction))))
                    .addComponent(jLabelPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInteractionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInteractionActionPerformed
		new InteractionFrame(this.controller, this.user);
    }//GEN-LAST:event_jButtonInteractionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonInteraction;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelNick;
    private javax.swing.JLabel jLabelPhoto;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JPanel jPanelStatus;
    // End of variables declaration//GEN-END:variables
}
