ex13: numeroDeOcorrencias.o main.o
	gcc numeroDeOcorrencias.o main.o -o ex13
numeroDeOcorrencias.o: numeroDeOcorrencias.c
	gcc -c numeroDeOcorrencias.c -o numeroDeOcorrencias.o
main.o: main.c 
	gcc -c main.c -o main.o
