  @startuml doc-files/ipc_3.1_extension_image2.png
  participant UIController as UIC
  participant ExtensionManager as ExtM
  participant "extension : WorkbookSearchExtension" as EExample
  participant "uiExtension : UIExtensionWorkbookSearch" as UIExt
  UIC -> ExtM : extensions=getExtensions();
  loop for Extension ext : extensions
  	UIC -> EExample : uiExtension=getUIExtension(this);
  	activate EExample
  	create UIExt
  	EExample -> UIExt : new
  	deactivate EExample
  	UIC -> UIC : uiExtensions.add(uiExtension);
  end
  @enduml