@startuml doc-files/design_IPC_4_3_Import.png
title Import from a database
actor Actor

  participant "ExportImportDatabaseAction" as Action
  participant "frame : ExportImportDatabaseFrame" as Frame
  participant "controller : ExportImportDatabaseController" as Controller

  note right of Actor
        Extention loading and integration with main UI can be found on Example Extention diagrams
  end note

  Actor-> UIFrame : select a range of cells
  Actor -> Action : starts use case
  create Frame
  Action -> Frame : new(UIController,IMPORT)
  create Controller
  Frame -> Controller : new(UIController)
  Frame --> Actor : ask For Database Connection
  Frame --> Actor : ask Table Name
  Frame -> Controller : saveSelectedCells(String Driver,String connection,String tableName)
  Controller -> DatabaseConnector : getInstance()
  Controller -> DatabaseConnector : setConnection(String Driver,String connection)
  Controller -> DatabaseConnector : doesTableExist(String tableName)
  alt table already exits
  Controller -> DatabaseConnector : data[][] =  getTable(String tableName)
  Controller -> UIController : getFocusOwner()
  Controller -> focusOwner : cells[][] = getSelectedCells()
  end
  loop cell : cells
  Controller -> Controller : cell.setContent(dats)
  end
@enduml